
<h2>Your ColdFusion app is running</h2>

If you can see formatted CFDUMP below, then you know it works!
<cfdump var=#cgi#>


If you don't see the CFDUMP output, make sure you have exploded cfusion.war (generated by the CF Installer) into webapp dir first.


